INPUT_FILES:
  Charges: Data/Charges_use.csv
  Damages: Data/Damages_use.csv
  Endorsements: Data/Endorse_use.csv
  Restrictions: Data/Restrict_use.csv
  Primary_Persons: Data/Primary_Person_use.csv
  Units: Data/Units_use.csv

OUTPUT_DIRECTORIES:
  1: ./Output/1
  2: ./Output/2
  3: ./Output/3
  4: ./Output/4
  5: ./Output/5
  6: ./Output/6
  7: ./Output/7
  8: ./Output/8
  9: ./Output/9
  10: ./Output/10

FILE_FORMAT:
  Output: csv